name: Flutter CI/CD

on:
  push:
    branches:
      - publish_to_fastlane_android
      
     
  pull_request:
    branches:
      - publish_to_fastlane_android
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code 
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Eclipse Temurin distribution
          java-version: '17'

      - name: Install Flutter stable channel
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          flutter-version: '3.38.3'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Our Test
        run: flutter test

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.6"
          bundler-cache: true
          working-directory: android


      - name: Deploy to Firebase via Fastlane
        working-directory: android
        
        env:
          FIREBASE_APP_ID: ${{ secrets.APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
        run: |
          bundle exec fastlane deploy_to_firebase